stages:
  - test

test-job:
  stage: test
  script:
    - echo "Running test job"
    - mkdir -p public
    - echo "<html><body><h1>Test Page</h1></body></html>" > public/index.html
  artifacts:
    paths:
      - public